# Generated by Django 4.2.8 on 2024-09-02 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_utilisateur_attestation_utilisateur_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('date_debut', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
