# Generated by Django 4.2.8 on 2025-01-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_utilisateur_status_universite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='quartier',
            field=models.CharField(blank=True, default='N/A', max_length=300, null=True, verbose_name='Quartier / ville'),
        ),
    ]
