# Generated by Django 4.2.8 on 2025-01-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
    ]
