# Generated by Django 4.2.8 on 2024-01-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancien_sujet', '0002_pays_document_date_document_document_document_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='miniature',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
