# Generated by Django 4.2.8 on 2024-03-19 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ancien_sujet', '0003_document_miniature_document_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='matiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ancien_sujet.matiere'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaiementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=512, unique=True)),
                ('payer', models.BooleanField(default=False)),
                ('moyen_paiement', models.CharField(choices=[('Orange Money', 'Orange Money'), ('Moov Money', 'Moov Money'), ('Sama Money', 'Sama Money'), ('Carte Visa', 'Carte Visa')], max_length=50)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(null=True)),
                ('montant', models.FloatField()),
                ('numero', models.CharField(max_length=30, null=True)),
                ('strip_link', models.URLField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancien_sujet.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAcheter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancien_sujet.document')),
            ],
        ),
    ]
