# Generated by Django 4.2.8 on 2024-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque_numerique', '0003_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
