# Generated by Django 4.2.8 on 2024-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque_numerique', '0004_auteur_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='document',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
